server:
  port: 8081
  servlet:
    context-path: /jwtapp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myjwtapp
    username:
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

jwt:
  token:
    secret: secretKeyForMyApplication
    expiration: 3600000
